name: GitHub Actions Demo
run-name: Testing out GitHub Actions 
on:
 push:
  branches:
      - master
      - 'releases/**'
  pull_request:
    branches:    
      - master
      - 'releases/**'

jobs:  
    runs-on: ubuntu-latest     
    steps:   
      - run: echo " Job is executing as part of Basic workflow" 
